### ISSUE TITLE
Tạo Album (thể loại)

### ISSUE THREAD

**Issue by luuthevinh** [LuuTheVinh/do-an-congngheweb-ungdung#1]
Lỗi này bị khi bấm tạo album, hình như bị lỗi ở chổ tạo mấy cái loại kia luôn.

![screenshot_20151229182612](https://cloud.githubusercontent.com/assets/9217534/12033776/d2a12694-ae59-11e5-8ab8-f463cec4bd2a.png)

**Comment by ChrisJamison** [comment]
Anh tạo bình thường mà. À bên anh set Id tự tăng nên Id không cần phải khởi tạo còn bên em ko set tự tăng nên khi khởi tạo sẽ bị lỗi

**Comment by ChrisJamison** [comment]
Em vào db set Id tự tăng rồi mới copy paste data qua

**Comment by hohoangtung** [comment]
nếu set id tự tăng sẽ sai tham chiếu hết

**Comment by ChrisJamison** [comment]
Không Em copy paste dữ liệu của anh qua có sẵn Id luôn rồi nên Id lúc đầu không tự tăng, sau này em tự nhập của em nó mới tự tăng
